### ISSUE TITLE
[Bug] Resources are not served with the base path env variable and the subpath nginx configuration requires a "/" proxy.

### ISSUE THREAD

**Issue by vishhvaan** [LukeChannings/moviematch#66]
**Describe the bug** The current nginx configuration for a subpath reverse proxy still requires the base bath "/" to be able to reverse proxy the port 8000 of moviematch. If I have plex.domain.com (which reverse proxies plex) and I want plex.domain.com/moviematch (to reverse proxy moviematch), I'm current unable to do this. If I remember correctly, I was able to do this in the past. 

**To Reproduce** Steps to reproduce the behavior:

1. Setup moviematch with the "/moviematch" env variable in Docker
2. ip_with_docker:8000/moviematch does not resolve but ip_with_docker:8000 does

**Expected behavior** The /moviematch path resolves with all resources served with the /moviematch base path. The nginx sub-path configuration only has one entry to reverse proxy "/moviematch/" without the need for "/"reverse proxy.

**Additional context** This is a really cool concept and you have implemented it very well. Thank you for making this!

**Comment by LukeChannings** [comment]
Can you please paste the exact Docker command / config wit your PLEX_URL or PLEX_TOKEN redacted?

Can you also paste a reduced example of your nginx config?

Also which version of MovieMatch are you using?

**Comment by vishhvaan** [comment]
Here's the docker-compose:  

moviematch:
   image: lukechannings/moviematch:latest
   container_name: moviematch
   environment:
    PLEX_URL: "http://ip_of_plexvm:32400"
    PLEX_TOKEN: "***"
    BASE_PATH: "/moviematch"
   ports:
      - 8000:8000

nginx conf:

    location ^~ /moviematch/ {
        proxy_pass http://ip_of_moviematch_vm:8000/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /moviematch;
    }

I tried this with the latest version on Docker hub and also the latest v2.

**Comment by LukeChannings** [comment]
Here's a complete `docker-compose.yaml` + `nginx.conf` for the latest version:

```yaml
version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:8000
  moviematch:
    image: lukechannings/moviematch:latest
    environment:
      PLEX_URL: "http://ip_of_plexvm:32400"
      PLEX_TOKEN: "***"
      ROOT_PATH: "/moviematch"
```

```nginx.conf
events {
  worker_connections 4096;
}

http {
  server {
    listen 8000;

    location ^~ /moviematch/ {
        proxy_pass http://moviematch:8000/;
        proxy_set_header Upgrade $http_upgrade;
    }
  }
}
```

You were using `BASE_PATH` (used in MovieMatch v2) instead of `ROOT_PATH` (used in MovieMatch v1). I'm considering reverting v2 back, since this is the second time this has caused confusion.

### v2

v2 is still unstable, and there's currently a bug with the posters not working in the latest alpha, this will be fixed in `2.0.0-alpha.5`.

```nginx.conf
events {
  worker_connections 4096;
}

http {
  server {
    listen 8000;

    location ^~ /moviematch/ {
        proxy_pass http://moviematch:8000/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-Prefix /moviematch;
    }
  }
}
```

```yaml
version: "3.3"
services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:8000
  moviematch:
    image: lukechannings/moviematch:2.0.0-alpha.4
    environment:
      PLEX_URL: "http://ip_of_plexvm:32400"
      PLEX_TOKEN: "***"
```
