### ISSUE TITLE
Setting Environment Variables

### ISSUE THREAD

**Issue by raddacle** [LukeChannings/moviematch#88]
I'm running the latest windows beta, and I've setup MovieMatch, but I can't figure out how to pass "REQUIRE_PLEX_LOGIN". I've tried entering it in the config file with no success. Is there a certain format that needs to be followed? I can't find any documentation on this.

**Comment by LukeChannings** [comment]
Hey @raddacle 

It's still in active development and the config is in flux, so I didn't want to duplicate documentation effort.

In the latest beta you can use [`requirePlexTvLogin: true`](https://github.com/LukeChannings/moviematch/blob/main/internal/app/moviematch/config/validate.ts#L218). 

In the next beta (hopefully), there will be a more sophisticated permissions system that looks like this:

```yaml
permittedAuthTypes:
  anonymous:
    - JoinRoom
  plex:
    - JoinRoom
  plexFriends:
    - JoinRoom
    - CreateRoom
  plexOwner:
    - JoinRoom
    - CreateRoom
    - DeleteRoom
    - ResetRoom
    - Admin
```

Roles:

- `anonymous` - anyone that just types a username and presses "log in"
- `plex` - anyone logging in with a plex.tv account
- `plexFriends` - only plex.tv accounts that you have shared your server with
- `plexOwner` - only the owner of any Plex server that's being used in the config

Permissions (self explanatory):

- JoinRoom
- CreateRoom
- DeleteRoom
- ResetRoom
- Admin

But for now the answer is `requirePlexTvLogin: true` :)
